# -*- coding: utf-8 -*-
"""Test_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JeOA7vh2Oc1H4UDRm_4Ue3W3wPMccV3N
"""

import time
from os import system

def clear(): 
  
    # for windows 
    if name == 'nt': 
        _ = system('cls') 
  
    # for mac and linux(here, os.name is 'posix') 
    else: 
        _ = system('clear') 


def efficientJanitor(n, weight):

  trip = 0

  while(True):

    bagWeight = 0
    items = []
    i = 0
    
    for x in weight:
      if( bagWeight + x <= 3 ):
        items.append(x)
        bagWeight = bagWeight + x

    for x in items:
      weight.remove(x)

    trip = trip + 1
    
    if not weight:
      print(trip)
      time.sleep(3)
      break

n = int(input())
weight = []
while( True ):
    a = float(input())
    if( a > 3):
        print("Input must be 0-3. Enter value again")
    else:
        weight.append(a)
    if(len(weight) == n):
        break
efficientJanitor(n, weight)



